### ISSUE TITLE
crash in android 4.4.4（com.airbnb.lottie.animation.content.BaseStrokeContent）

### ISSUE THREAD

**Issue by friendlove** [react-community/lottie-react-native#321]
java.lang.NullPointerException
	at com.airbnb.lottie.animation.content.BaseStrokeContent.<init>(BaseStrokeContent.java:61)
	at com.airbnb.lottie.animation.content.StrokeContent.<init>(StrokeContent.java:25)
	at com.airbnb.lottie.model.content.ShapeStroke.toContent(ShapeStroke.java:77)
	at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
	at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
	at com.airbnb.lottie.model.content.ShapeGroup.toContent(ShapeGroup.java:29)
	at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
	at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
	at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:25)
	at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:44)
	at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
	at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:236)
	at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:198)
	at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:488)
	at com.airbnb.lottie.LottieAnimationView$1.onCompositionLoaded(LottieAnimationView.java:81)
	at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:29)
	at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:12)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5113)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by xipgroc** [comment]
Got the same crash, using both real and emulated devices, using android 4.2.2 and 4.4.4. 
Works OK using android 5 and upwards.

Tested using lottie version 2.3.2, 2.5.0, 2.2.7, it crashes both with and without hardware acceleration. The app works fine, and suddenly crashes as soon as I navigate to the view with the lottie animation

**Comment by martinspaeth** [comment]
Same here...

**Comment by TobiasReich** [comment]
Me, too. Using Lottie 2.5.4

Seems to be crashing only on devices below Android 5 but that might be coincidence.

**Comment by manuhook** [comment]
Same here
Android < 4

**Comment by treemore** [comment]
https://github.com/airbnb/lottie-android/issues/759

**Comment by yk3372** [comment]
this maybe help you #351
